language: node_js
node_js:
  - 14
before_install:
  - openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
    -in .travis/id_rsa.enc -out id_rsa -d
after_success:
  - ./travis/deploy.sh
